deathrr/urls.py
from django.urls import path, include
from . import views

app_name = 'deathrr'

urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('code_range_home', views.range_home_view, name="range_home"),
    path('filter_reports/', views.filter_reports_view, name="filter_reports"),
    path('filter_range_reports/', views.filter_range_reports_view, name="filter_range_reports"),
    path('create_deceased_report/', views.create_deceased_report, name='create_deceased_report'),
    path('update_deceased_report/<int:pk>/<str:return_screen>', views.update_deceased_report, name='update_deceased_report'),
    path('view_deceased_report/<int:pk>/<str:return_screen>', views.view_deceased_report, name='view_deceased_report'),
    path('delete_deceased_report/<int:pk>/<str:return_screen>', views.delete_report, name='delete_deceased_report'),
    path('delete_deceased_code/<int:d_pk>/<int:c_pk>', views.delete_deceased_code, name='delete_deceased_code'),
    path('add_code/<int:pk>', views.add_code, name='add_code'),
    path('download_count_reports', views.download_count_reports, name="download_count_reports"),
    path('download_detail_reports', views.download_detail_reports, name="download_detail_reports"),
    path('find_code', views.find_and_add_icd_code, name='find_and_add_code'),
    path('add_icd_code/<int:pk>/<str:return_screen>', views.add_icd_code_view, name='add_icd_code_view')
]

deathrrproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('death_recording_and_reporting/', include('deathrr.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('reset_password', views.reset_password_view, name='reset_password'),
    path('reset_password_success', views.reset_password_successful_view, name='reset_password_success'),
]

deathrr/models.py
import datetime

from django.db import models


class DeceasedEntry(models.Model):
    id = models.BigAutoField(primary_key=True)
    created_by = models.CharField(max_length=100, null=True, blank=True, default="jill.sain@cherokeehospital.org")
    last_modified_by = models.CharField(max_length=100, null=True, blank=True, default="")
    deleted_flag = models.BooleanField(null=True, blank=True, default=False)
    name = models.CharField(max_length=100, null=True, blank=True)
    chart_num = models.CharField(max_length=15, null=True, blank=True)
    dob = models.DateField(null=True, blank=True, default=datetime.date(2030,1,1))
    state_where_died = models.CharField(max_length=15, null=True, blank=True, default="North Carolina")
    death_cert_num = models.CharField(max_length=20, null=True, blank=True)
    dod = models.DateField(null=False, blank=False)
    place_of_death = models.CharField(max_length=50,null=True, blank=True)
    race = models.CharField(max_length=80, null=True, blank=True)
    autopsy_performed = models.BooleanField(default=False)
    manner_of_death = models.CharField(max_length=30, null=True, blank=True)
    death_by_work_injury = models.BooleanField(default=False)
    place_of_injury = models.CharField(max_length=50, blank=True, null=True)
    method_of_verification = models.CharField(max_length=50, default="")

    empty_value_display = "-empty-"


class ICDCode(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=10, default="")
    description = models.CharField(max_length=100, default="")
    type = models.CharField(max_length=2, default="")
    ien = models.IntegerField(default=1)

    def __str__(self):
        return str(self.code) + " - " + str(self.description)


class DeceasedCodes(models.Model):
    id = models.BigAutoField(primary_key=True)
    code_id = models.ForeignKey(ICDCode, on_delete=models.CASCADE)
    deceased_id = models.ForeignKey(DeceasedEntry, on_delete=models.CASCADE)
    is_primary = models.BooleanField(default=False)

deathrr/views.py
import json
# import pandas as pd

from django.shortcuts import render
import datetime
from django.utils import timezone
from .models import DeceasedEntry, DeceasedCodes, ICDCode
from .forms import DeceasedEntryForm, NewCodeForm, NewICDCodeForm
from django.shortcuts import redirect, reverse
from django.contrib.auth.decorators import login_required
from django.db import connections, connection
from django.http import JsonResponse, HttpResponse
from collections import Counter





@login_required(login_url="/users/login")
def home_view(request):
    states = [ "-----",
        "ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO",
        "CONNECTICUT", "DELAWARE", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO",
        "ILLINOIS", "INDIANA", "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA",
        "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA",
        "MISSISSIPPI", "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE",
        "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA",
        "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA",
        "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "VERMONT", "VIRGINIA",
        "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING"
    ]

    special_filters = ["-----", "All Reports", "All Reports in Date Range", "All Reports with No Codes", "All Reports with 'Pending Investigation'"]
    # if request.GET.get('start_code'):
    #     request.session['start_code'] = request.GET.get('start_code')
    # elif request.GET.get('end_code'):
    #     request.session['end_code'] = request.GET.get('end_code')
    if request.GET.get('filter_start_date'):
        start_date = request.GET.get('filter_start_date')
        request.session['start_date'] = start_date
    elif request.GET.get('filter_end_date'):
        end_date = request.GET.get('filter_end_date')
        request.session['end_date'] = end_date
    if request.session.get('start_date'):
        start_date = datetime.datetime.strptime(request.session.get('start_date'), '%Y-%m-%d').date()
    else:
        start_date = datetime.date.today()
    if request.session.get('end_date'):
        end_date = datetime.datetime.strptime(request.session.get('end_date'), '%Y-%m-%d').date()
    else:
        end_date = datetime.date.today()
    filter_state = request.session.get('state', '-----')
    start_code = request.session.get('start_code', '')
    end_code = request.session.get('end_code', '')
    filter_text = request.session.get('filter_text', '')
    filter_code = request.session.get('filter_code', '')
    filter_primary = request.session.get('filter_primary', False)
    special_filter = request.session.get('special_filter', "-----")

    return render(request, 'deathrr/home.html', {'start_date': start_date, 'end_date': end_date, 'filter_code': filter_code, 'states':states, 'selected_state': filter_state, 'filter_text': filter_text,
                                                 'filter_primary': filter_primary, 'special_filters': special_filters, 'selected_special_filter': special_filter, 'start_code': start_code, 'end_code': end_code})

@login_required(login_url="/users/login")
def range_home_view(request):

    start_date = request.session.get('range_start_date', str(datetime.date.today()))
    start_date = datetime.datetime.strptime(start_date, '%Y-%m-%d').date()
    request.session['range_start_date'] = str(start_date)

    end_date = request.session.get('range_end_date', str(datetime.date.today()))
    end_date = datetime.datetime.strptime(end_date, '%Y-%m-%d').date()
    request.session['range_end_date'] = str(end_date)
    codes = ICDCode.objects.all().order_by('code').values_list('code', flat=True)
    start_code = request.session.get('range_start_code', codes[0])
    default_start_code = codes[0]
    default_end_code = codes[len(codes)-1]
    end_code = request.session.get('range_end_code', codes[len(codes)-1])
    filter_text = request.session.get('range_filter_text', '')
    return render(request, 'deathrr/code_range_home.html', {'range_start_date': start_date, 'range_end_date': end_date, 'range_filter_text': filter_text,'range_start_code': start_code, 'range_end_code': end_code, 'default_sc': default_start_code, 'default_ec': default_end_code})

@login_required(login_url="/users/login")
def filter_reports_view(request):

    if request.GET.get('special_filter'):

        request.session['special_filter'] = request.GET.get('special_filter')

    elif request.GET.get('filter_start_date'):
        request.session['start_date'] = request.GET.get('filter_start_date')
    elif request.GET.get('filter_end_date'):
        request.session['end_date'] = request.GET.get('filter_end_date')
    elif request.GET.get('filter_primary'):
        request.session['filter_primary'] = True if request.GET.get('filter_primary') == "on" else False
    elif request.GET.get('filter_state'):
        request.session['state'] = request.GET.get('filter_state')
    elif request.GET.get('filter_text'):
        request.session['filter_text'] = request.GET.get('filter_text')

    elif 'filter_text' in request.GET and not request.GET.get('filter_text'):
        request.session['filter_text'] = ""
    elif request.GET.get('start_code'):
        request.session['start_code'] = request.GET.get('start_code')
    elif request.GET.get('end_code'):
        request.session['end_code'] = request.GET.get('end_code')
    else:
        request.session['filter_primary'] = False
    start_date = request.session.get('start_date', str(datetime.date.today()))
    end_date = request.session.get('end_date', str(datetime.date.today()))

    # added_start_time = datetime.timedelta(hours=0, minutes=0, seconds=0)
    # added_time = datetime.timedelta(hours=23, minutes=59, seconds=59)
    # start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d")
    # end_date = datetime.datetime.strptime(end_date, "%Y-%m-%d")
    # start_date += added_start_time
    # start_date = timezone.make_aware(start_date)
    # end_date += added_time
    # end_date = timezone.make_aware(end_date)

    filter_primary = request.session.get('filter_primary', False)
    special_filter = request.session.get('special_filter', "-----")
    state = request.session.get('state', '-----')
    filter_text = request.session.get('filter_text', '')
    if special_filter == "-----":
        if state == '-----':
            filtered_reports = DeceasedEntry.objects.filter(dod__gte=start_date, dod__lte=end_date, deleted_flag=0).order_by('dod')
        else:
            filtered_reports = DeceasedEntry.objects.filter(dod__gte=start_date, dod__lte=end_date, state_where_died=state, deleted_flag=0).order_by('dod')
        if filter_text != '':
            if is_code(filter_text):
                report_ids = filtered_reports.values_list('id', flat=True)
                filter_code_id = ICDCode.objects.filter(code=filter_text).values_list('id', flat=True)

                if not filter_primary:
                    filtered_mapper = DeceasedCodes.objects.filter(deceased_id__in=report_ids, code_id__in=filter_code_id).values_list('deceased_id', flat=True)
                else:
                    filtered_mapper = DeceasedCodes.objects.filter(deceased_id__in=report_ids, code_id__in=filter_code_id, is_primary=1).values_list('deceased_id', flat=True)
                filtered_reports = filtered_reports.filter(id__in=filtered_mapper).order_by('dod')

                request.session['download_count_data'] = json.dumps(list(filtered_reports.values_list('id', flat=True)))

                return render(request, 'deathrr/partials/report_list.html', {'reports': filtered_reports, 'reports_size': len(filtered_reports), 'return_screen': True})
            else:
                description_filtered_reports = []
                report_ids = filtered_reports.values_list('id', flat=True)
                codes_counter = {}
                filtered_codes = ICDCode.objects.filter(description__icontains=filter_text)
                if filter_primary:
                    filtered_mapper = DeceasedCodes.objects.filter(deceased_id__in=report_ids, is_primary=1).values_list('code_id', flat=True)
                else:
                    filtered_mapper = DeceasedCodes.objects.filter(deceased_id__in=report_ids).values_list('code_id', flat=True)
                code_dict = {code.id: code for code in filtered_codes}
                for code in filtered_mapper:
                    if code in code_dict:
                        if code in codes_counter:
                            codes_counter[code] += 1
                        else:
                            codes_counter[code] = 1
                if len(codes_counter) > 0:
                    for key in codes_counter.keys():
                        description_filtered_reports.append({'count': codes_counter[key], 'description': code_dict[key].description, 'code':code_dict[key].code})

                if len(description_filtered_reports) > 0:
                   description_filtered_reports = sorted(description_filtered_reports, key=lambda x: x['count'], reverse=True)
                request.session['download_count_data'] = json.dumps(description_filtered_reports)
                return render(request, 'deathrr/partials/report_list_count.html', {'reports': description_filtered_reports, 'reports_size': len(description_filtered_reports)})
        else:
            all_filtered_reports = []
            report_ids = filtered_reports.values_list('id', flat=True)
            codes_counter = {}
            if filter_primary:
                filtered_mapper = DeceasedCodes.objects.filter(deceased_id__in=report_ids, is_primary=1).values_list(
                    'code_id', flat=True)
            else:
                filtered_mapper = DeceasedCodes.objects.filter(deceased_id__in=report_ids).values_list('code_id', flat=True)
            for code in filtered_mapper:
                if code in codes_counter:

deathrr/templates/deathrr/partials/deceased_codes_list.html
{% load crispy_forms_tags %}
{% load static %}
<div id="divid">
    <div style="height:300px; overflow-y:scroll;">
<table class="table table-hover mx-auto mt-5" style="background-color:white; width:60%;" id="codes_table" >
    <thead class="sticky-top bg-light">
    <tr>
        <th scope="col">Code</th>
        <th scope="col">Description</th>
        <th scope="col">Type</th>
        <th scope="col">Is Primary COD</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
  {% if codes_size > 0 %}
  {% for code in existing_codes %}
    <tr>
      <th scope="row">{{code.code}}</th>
      <td>{{code.description}}</td>
        <td>{{code.type}}</td>
        {% if code.is_primary %}
        <td>Yes</td>
        {% else %}
        <td>No</td>
        {% endif %}
        <td><form style="display:inline-block" id="deleteForm" hx-post="{% url 'deathrr:delete_deceased_code' pk code.id %}" method="post" hx-target="#divid"> {% csrf_token %} <button class="btn btn-danger">Delete</button></form></td>
    </tr>
  {% endfor%}
  {% else %}
  <tr>
    <td>No codes have been added yet</td>
  </tr>
  {% endif %}
</table>
        </div>
<form method="post" id="add-code-form">
    <div class="d-flex flex-row" style="margin-left:20%">
        <div class="p-2">{{new_code_form.code_id|as_crispy_field}}</div>
        <div class="p-5" style="margin-top:3px;">{{new_code_form.is_primary|as_crispy_field}}</div>
        <div class="p-5 mb-5" style="margin-right:40px;"><button class="btn btn-success" type="submit" form="add-code-form" name="add_codes_btn" hx-trigger="click" hx-post="{% url 'deathrr:add_code' pk %}" hx-target="#codes_list">Add</button></div>
    </div>
</form>

<!--    <div class="mt-4 mb-4">-->
<!--            <label id="invalid_code_lable" style="color:red;" hidden>Invalid Code Entered.</label>-->
<!--            <label for="code_text" >Enter code manually:</label>-->
<!--&lt;!&ndash;            <input id="code_text" value="{{ filter_text }}" name="code_text" hx-trigger="blur" hx-get="{% url 'deathrr:find_and_add_code' %}" hx-on="htmx:afterRequest: handleResponse">&ndash;&gt;-->
<!--            <input id="code_text" value="{{ filter_text }}" name="code_text">-->

<!--    </div>-->
    <script>
        document.getElementById("code_text").addEventListener("blur", function() {
            const enteredCode = document.getElementById("code_text").value;
            fetch("{% url 'deathrr:find_and_add_code' %}?code_text=" + encodeURIComponent(enteredCode))
                .then(response => response.json())
                .then(data => {
                    // Handle the response from the server
                    if (data.code_ien != -1) {
                        document.getElementById("code_text").style.color = "green";
                        alert(data.code_ien);
                    } else {
                        document.getElementById("code_text").style.color = "red";
                        console.log("The code is invalid.");
                    }
                })
                .catch(error => {
                    console.error("Error:", error);
                });
        });
    </script>

</div>

deathrr/templates/deathrr/partials/report_list.html
<div id="rep_tab">
    <p class="text-center">Reports found: {{reports_size}}</p>
    <div style = "height:400px; overflow-y:scroll;">
<table class="table table-hover ml-4 mr-4 mt-4" style="background-color:white;" id="reports_table">
    <thead class="sticky-top bg-light">
    <tr><th scope="col">Name</th>
      <th scope="col">HRN</th>
        <th scope="col">Date of Birth</th>
      <th scope="col">Date of Death</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
  {% if reports_size > 0 %}
  {% for report in reports %}
    <tr>
        {% if report.name %}
        <th scope="row">{{report.name}}</th>
        {% else %}
        <th scope="row">------</th>
        {% endif %}
        {% if report.chart_num %}
        <td>{{report.chart_num}}</td>
        {% else %}
        <td>------</td>
        {% endif %}
        {% if report.dob %}
        <td>{{report.dob}}</td>
        {% else %}
        <td>------</td>
        {% endif %}
        <td>{{report.dod}}</td>
        <td>
            <form style="display:inline-block; border:none;" method="get" action="{% url 'deathrr:view_deceased_report' report.id return_screen %}"> {% csrf_token %} <button style="border:none; background:white;" class=""><i class="bi bi-eye-fill"></i></button></form>
            <form style="display:inline-block; border:none;" method="get" class="" action="{% url 'deathrr:update_deceased_report' report.id return_screen %}">{% csrf_token %} <button style="border:none; background:white;" class=""><i class="bi bi-pencil-square"></i></button></form>
            <form style="display:inline-block; border: none;" id="deleteForm" hx-post="{% url 'deathrr:delete_deceased_report' report.id return_screen %}" method="post" hx-target="#rep_tab"> {% csrf_token %} <button style="border:none; background:white; color:red;" class=""><i class="bi bi-x-lg"></i></button></form>
        </td>
    </tr>
  {% endfor%}
  {% else %}
  <tr>
    <td>No data for selected dates</td>
  </tr>
  {% endif %}
</table>

    </div>
    {% if reports_size > 0 %}
        <a href="{% url 'deathrr:download_detail_reports' %}"><button class="btn btn-secondary mr-5" style="margin-right:80px" type="button">Download</button></a>
    {% endif %}
</div>

deathrr/templates/deathrr/partials/report_list_count.html
<div id="rep_tab">
    <p class="text-center">Reports found: {{reports_size}}</p>
    <div style = "height:400px; overflow-y:scroll;">
<table class="table table-hover ml-4 mr-4 mt-4"  style="background-color:white;" id="reports_table">
    <thead class="sticky-top bg-light">
    <tr><th scope="col"># of Entries</th>
      <th scope="col">Description</th>
      <th scope="col">ICD10</th>
    </tr>
    </thead>
    <tbody>
  {% if reports_size > 0 %}
  {% for report in reports %}
    <tr onclick="addCodeToSearch(this)" style="cursor: pointer;">
        <th scope="row">{{report.count}}</th>
        <td>{{report.description}}</td>
        <td>{{report.code}}</td>
    </tr>
  {% endfor%}
  {% else %}
  <tr>
    <td>No data for selected dates</td>
  </tr>
  {% endif %}
</table>
        </div>
    {% if reports_size > 0 %}
        <a href="{% url 'deathrr:download_count_reports' %}"><button class="btn btn-secondary mr-5" style="margin-right:80px" type="button">Download</button></a>
    {% endif %}
    <script>
        function addCodeToSearch(row) {
            const rowCode = row.getElementsByTagName('td')[1].innerText
            const filterTextBox = document.getElementById('filter_text');
            const specialFilterTextBox = document.getElementById('special_filter');

            filterTextBox.value = rowCode;
            htmx.trigger(filterTextBox, 'blur');

        }
    </script>
</div>