deathrr/urls.py
from django.urls import path, include
from . import views

app_name = 'deathrr'

urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('code_range_home', views.range_home_view, name="range_home"),
    path('filter_reports/', views.filter_reports_view, name="filter_reports"),
    path('filter_range_reports/', views.filter_range_reports_view, name="filter_range_reports"),
    path('create_deceased_report/', views.create_deceased_report, name='create_deceased_report'),
    path('update_deceased_report/<int:pk>/<str:return_screen>', views.update_deceased_report, name='update_deceased_report'),
    path('view_deceased_report/<int:pk>/<str:return_screen>', views.view_deceased_report, name='view_deceased_report'),
    path('delete_deceased_report/<int:pk>/<str:return_screen>', views.delete_report, name='delete_deceased_report'),
    path('delete_deceased_code/<int:d_pk>/<int:c_pk>', views.delete_deceased_code, name='delete_deceased_code'),
    path('add_code/<int:pk>', views.add_code, name='add_code'),
    path('download_count_reports', views.download_count_reports, name="download_count_reports"),
    path('download_detail_reports', views.download_detail_reports, name="download_detail_reports"),
    path('find_code', views.find_and_add_icd_code, name='find_and_add_code'),
    path('add_icd_code/<int:pk>/<str:return_screen>', views.add_icd_code_view, name='add_icd_code_view')
]

deathrrproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('death_recording_and_reporting/', include('deathrr.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('reset_password', views.reset_password_view, name='reset_password'),
    path('reset_password_success', views.reset_password_successful_view, name='reset_password_success'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <title>
        {% block title %}
            CIHA Death Recording and Reporting App
        {% endblock %}
    </title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="icon" href="{% static 'favicon.ico' %}" >

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
</head>
<body style="background-color: rgb(226,240,220);">
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        });
        window.addEventListener('beforeunload', function(event) {
            sessionStorage.clear(); // Clear session storage when the tab is closed
        });
    </script>
    <nav class="navbar navbar-expand-lg me-5 ms-5" style="background-color:rgb(158,174,137);">
        <h2 class="navbar-brand" style="margin-left:10px">Welcome</h2>
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav justify-content-start">
                    <li class="nav-item active">
                        <form action="{% url 'deathrr:home' %}" method="post">
                            {% csrf_token %}
                            <button class="btn my-2 my-sm-0" style="background-color: rgb(0,0,0,0); border: none; color: black" type="submit">Home</button>
                        </form>
                    </li>
                    <li class="nav-item active">
                        <a href="{% url 'deathrr:range_home' %}"><button class="btn my-2 my-sm-0" style="background-color: rgb(0,0,0,0); border: none; color: black" type="button">Report by Code Range</button></a>
                    </li>
                    <li class="nav-item active">
                        <a href="{% url 'deathrr:create_deceased_report' %}"><button class="btn my-2 my-sm-0" style="background-color: rgb(0,0,0,0); border: none; color: black" type="button">Create Report</button></a>
                    </li>
                    <li class="nav-item active">
                        <a href="{% url 'deathrr:add_icd_code_view' 0 0 %}"><button class="btn my-2 my-sm-0" style="background-color: rgb(0,0,0,0); border: none; color: black" type="button">Add New ICD Code</button></a>
                    </li>
                </ul>
                <a class="ms-auto ml-auto" style="color:black; text-decoration: none;">Logged in as:</a>
                <ul class="navbar-nav justify-content-start">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle me-3 margin-right: 50x;" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:black">{{user.username}}</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="nav-item ms-auto me-3">
                                <a class="dropdown-item" href="{% url 'users:reset_password' %}">Change Password</a>
                            </li>
                            <li class="nav-item active">
                                <form action="{% url 'users:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn my-2 my-sm-0 me-3" style="background-color: rgb(0,0,0,0); border: none; color: black" type="submit">Logout</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>
                <img src="{% static 'CIHA_Seal.png' %}" alt="CIHA Seal" style="width:85px; margin-right:20px;">
            </div>
        {% endif %}
    </nav>
<main class="m-5">
    {% block content %}{% endblock %}
</main>
</body>
</html>